export let students = [
  {
    name: 'Гарри',
    middlename: 'Джеймсович',
    surname: 'Поттер',
    faculty: 'Гриффиндор',
    dateBirth: '1980-07-31',
    startEdu: '1996-09-01',
  },
  {
    name: 'Драко',
    middlename: 'Люциус',
    surname: 'Малфой',
    faculty: 'Слизерин',
    dateBirth: '1980-06-05',
    startEdu: '1996-09-01',
  },
  {
    name: 'Том',
    middlename: 'Марволо',
    surname: 'Реддл',
    faculty: 'Слизерин',
    dateBirth: '1926-12-31',
    startEdu: '1932-09-01',
  },
  {
    name: 'Северус',
    middlename: 'Жёлтый',
    surname: 'Снегг',
    faculty: 'Слизерин',
    dateBirth: '1960-11-03',
    startEdu: '1976-09-01',
  },
  {
    name: 'Тестировщик',
    middlename: 'Этого',
    surname: 'Массива',
    faculty: 'Разработка',
    dateBirth: '1982-11-03',
    startEdu: '2018-09-01',
  },
]
